# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7d3c63981bc8b0b9b105413d4060ebd9c886d3b0aa34f574fed23fa7ea88252898c55e8a558eedf802a6cb911c577630d48c55f44699818b5611645eb513b05

test:
  secret_key_base: f387733e5bb5e959a10f49392ef7a19a7c57ac65927788ece60ddc9407edcaa9309a3a590e7eb7a1a6fa01e70352cef1ef770426d29df8ff5f43167ae8c6ee55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
